services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    network_mode: "slirp4netns:allow_host_loopback=true"
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    network_mode: "slirp4netns:allow_host_loopback=true"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
  podman-exporter:
    container_name: podman-exporter
    image: quay.io/navidys/prometheus-podman-exporter
    command:
      - '--collector.enable-all'
    environment:
      - CONTAINER_HOST=unix:///run/podman/podman.sock
    volumes:
      - /run/user/1000/podman/podman.sock:/run/podman/podman.sock
    ports:
      - 9882:9882
    security_opt:
      - label=disable
#    userns_mode: keep-id:uid=65534

volumes:
  prom_data:
